### ISSUE TITLE
Class Spyc not found

### ISSUE THREAD

**Issue by jmares79** [Celc/CIUnit#17]
Hi guys, I'm trying to use CIUnit, installed as explained, but when trying to run them, it says:

Fatal error: Class 'Spyc' not found in C:\xampp\htdocs\project\vendor\celc\ciunit\src\bootstrap_phpunit.php on line 243

I checked that the class is effectively is in vendor\mustangostang\spyc\Spyc.php

Any ideas of waht could be heppening?

Thanks!

**Comment by Celc** [comment]
Closing since there's no updates.

@thominj Thanks for pointing that out. Packages add their callable to vendor/bin if you want to avoid tricksters. I've updated the readme to specifically mention `../vendor/bin/phpunit` since I can see how that can be hard to debug.
