### ISSUE TITLE
Fatal error: Call to undefined function get_instance() in /vendor/celc/ciunit/src/libraries/CIUnitTestCase.php on line 76

### ISSUE THREAD

**Issue by junaidatique** [Celc/CIUnit#20]
Hey,

I am getting following error

Fatal error: Call to undefined function get_instance() in /opt/lampp/htdocs/ci_phpunit/vendor/celc/ciunit/src/libraries/CIUnitTestCase.php on line 76

I am using PHPStorm 8.0 with PHP 5.6. I have installed this as composer package.

Also please update the installation notes. they are kind of confusing. 

Please help.

**Comment by Celc** [comment]
What version of CodeIgniter are you running. What portion of the documentation is confusing?

**Comment by Celc** [comment]
Also what's the path to your application folder?

**Comment by junaidatique** [comment]
Codeigniter version is 2.1.4. I have fresh installation of codeigniter. phpunit that is downloaded by composer is 4.2.6. 
The application folder is in the main folder where I have copied tests. system is also in the same folder.

Documentation is confusing as I don't know where to put my custom tests. Well that comes later as I can't run the predefined tests.

Thanks for quick reply. I have spend 8+ hours in order to fix this error. Thanks for your cooperation.

**Comment by Celc** [comment]
CIUnit isn't tested on 2.1.x, but it appears to be working:

```bash
wget https://github.com/bcit-ci/CodeIgniter/archive/2.1.4.zip
cd CodeIgniter-2.1.4
composer init --no-interraction
composer require Celc/ciunit dev-master
cp -R vendor/Celc/ciunit/tests ./
cd tests
../vendor/bin/phpunit
```

Gives

```bash
[CIUnit] PHP Error: Notice - Only variable references should be returned by reference File Path: core/Common.php (line: 164)
PHPUnit 4.2.6 by Sebastian Bergmann.

Configuration read from /Users/kitsunde/Development/CodeIgniter-2.1.4/tests/phpunit.xml.dist

....
Sorry, the name of your test database must end on '_test'.
This prevents deleting important data by accident.
```

After you've copied the test folder to the root of your CodeIgniter project (in your case it should be `/opt/lampp/htdocs/ci_phpunit/` if your `application` directory is also in `/opt/lampp/htdocs/ci_phpunit/`). Please ensure you've replicated the above and that paths to `test` and `application` folders are siblings. Also please ensure that the version of phpunit that is running is 4.x.

**Comment by junaidatique** [comment]
Thanks Dear. This fixed this.

The error was because I was using using the following command in the root directory

/vendor/bin/phpunit ./tests/

But last two commands of your work has fixed the code.
